{
    "openapi": "3.0.0",
    "info": {
        "title": "SKU Bindings API",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br/api",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "{accountName}"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "default": "{environment}"
                }
            }
        }
    ],
    "paths": {
        "/catalog/pvt/skusellers/{skuId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get by SkuId",
                "operationId": "GetbySkuId",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/internal/paginate": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get by SkuId internal paged",
                "operationId": "GetbySkuIdinternalpaged",
                "parameters": [
                    {
                        "name": "skuId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{skuId}"
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{page}"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{size}"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/admin": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get paged admin",
                "operationId": "Getpagedadmin",
                "parameters": [
                    {
                        "name": "sellerId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{sellerId}"
                        }
                    },
                    {
                        "name": "skuId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{skuId}"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{sellerSkuId}"
                        }
                    },
                    {
                        "name": "isActive",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{isActive}"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{size}"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/{sellerId}/{sellerSkuId}": {
            "get": {
                "tags": [
                    "SKU Seller"
                ],
                "summary": "Get details of a seller's SKU",
                "description": "Retrieves the details of a seller's SKU given a seller ID and the SKU ID in the seller's store. \r\n## Response body example\r\n\r\n```json\r\n{\r\n    \"IsPersisted\": true,\r\n    \"IsRemoved\": false,\r\n    \"SkuSellerId\": 799,\r\n    \"SellerId\": \"myseller\",\r\n    \"StockKeepingUnitId\": 50,\r\n    \"SellerStockKeepingUnitId\": \"502\",\r\n    \"IsActive\": true,\r\n    \"UpdateDate\": \"2018-10-11T04:52:42.1\",\r\n    \"RequestedUpdateDate\": null\r\n}\r\n```",
                "operationId": "GetSKUseller",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "101"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "IsPersisted",
                                        "IsRemoved",
                                        "SkuSellerId",
                                        "SellerId",
                                        "StockKeepingUnitId",
                                        "SellerStockKeepingUnitId",
                                        "IsActive",
                                        "UpdateDate",
                                        "RequestedUpdateDate"
                                    ],
                                    "properties": {
                                        "IsPersisted": {
                                            "type": "boolean",
                                            "description": "Defines if the seller is persisted."
                                        },
                                        "IsRemoved": {
                                            "type": "boolean",
                                            "description": "Defines if the seller is removed."
                                        },
                                        "SkuSellerId": {
                                            "type": "integer",
                                            "format": "int32",
                                            "description": "SKU ID in the seller's store."
                                        },
                                        "SellerId": {
                                            "type": "string",
                                            "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                        },
                                        "StockKeepingUnitId": {
                                            "type": "integer",
                                            "format": "int32",
                                            "description": "SKU ID in the VTEX marketplace."
                                        },
                                        "SellerStockKeepingUnitId": {
                                            "type": "string",
                                            "description": "SKU seller ID."
                                        },
                                        "IsActive": {
                                            "type": "boolean",
                                            "description": "Defines if the SKU binding is active."
                                        },
                                        "UpdateDate": {
                                            "type": "string",
                                            "description": "Date when the SKU binding was updated for the last time, in UTC format."
                                        },
                                        "RequestedUpdateDate": {
                                            "type": "string",
                                            "description": "Date when an SKU binding update was requested for the last time, in UTC format.",
                                            "nullable": true
                                        }
                                    },
                                    "example": {
                                        "IsPersisted": true,
                                        "IsRemoved": false,
                                        "SkuSellerId": 799,
                                        "SellerId": "myseller",
                                        "StockKeepingUnitId": 50,
                                        "SellerStockKeepingUnitId": "502",
                                        "IsActive": true,
                                        "UpdateDate": "2018-10-11T04:52:42.1",
                                        "RequestedUpdateDate": null
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/list/bysellerId/{sellerId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get all by SellerId",
                "operationId": "GetallbySellerId",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/paged/sellerid/{sellerId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get paged by SellerId",
                "operationId": "GetpagedbySellerId",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{page}"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{size}"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/changenotification/{stockKeepingUnitId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification by SkuId",
                "operationId": "ChangenotificationbySkuId",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "stockKeepingUnitId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification by SkuId1",
                "operationId": "ChangenotificationbySkuId1",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "stockKeepingUnitId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/changenotification/{sellerId}/{sellerSkuId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification by SellerId and SkuSellerId",
                "operationId": "ChangenotificationbySellerIdandSkuSellerId",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification by SellerId and SkuSellerId1",
                "operationId": "ChangenotificationbySellerIdandSkuSellerId1",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/insertion": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Insert",
                "operationId": "Insert",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/InsertRequest"
                            },
                            "example": {
                                "StockKeepingUnitId": 123,
                                "IsActive": true,
                                "SellerId": "seller1",
                                "SellerStockKeepingUnitId": "ABC123"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/activate/{sellerId}/{sellerSkuId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Activate",
                "operationId": "Activate",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/inactivate/{sellerId}/{skuSellerId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Deactivate",
                "operationId": "Deactivate",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "skuSellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/remove/{sellerId}/{sellerSkuId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Delete",
                "operationId": "Delete",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "sellerId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/catalog_system/pvt/skuseller/report": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Report",
                "operationId": "Report",
                "parameters": [
                    {
                        "name": "sellerId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{sellerId}"
                        }
                    },
                    {
                        "name": "skuId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{skuId}"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{sellerSkuId}"
                        }
                    },
                    {
                        "name": "isActive",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "{isActive}"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        }
    },
    "security": [
        {
            "appKey": [],
            "appToken": []
        }
    ],
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        },
        "schemas": {
            "InsertRequest": {
                "title": "InsertRequest",
                "required": [
                    "StockKeepingUnitId",
                    "IsActive",
                    "SellerId",
                    "SellerStockKeepingUnitId"
                ],
                "type": "object",
                "properties": {
                    "StockKeepingUnitId": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "IsActive": {
                        "type": "boolean"
                    },
                    "SellerId": {
                        "type": "string"
                    },
                    "SellerStockKeepingUnitId": {
                        "type": "string"
                    }
                },
                "example": {
                    "StockKeepingUnitId": 123,
                    "IsActive": true,
                    "SellerId": "seller1",
                    "SellerStockKeepingUnitId": "ABC123"
                }
            },
            "BindtoanotherskuRequest": {
                "title": "BindtoanotherskuRequest",
                "required": [
                    "StockKeepingUnitId"
                ],
                "type": "object",
                "properties": {
                    "StockKeepingUnitId": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "StockKeepingUnitId": 123
                }
            }
        }
    },
    "tags": [
        {
            "name": "SKU Bindings"
        }
    ]
}